# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

## Site
title: Chunk Blog           # 博客标题
subtitle: 我的个人博客       # 博客副标题
description: Hexo 搭建的个人博客，用于分享学习笔记和经验
keywords: Hexo, 博客, 学习, 笔记
author: chunk               # 博主名字
language: zh-CN             # 语言
timezone: Asia/Shanghai      # 时区

# URL
url: https://subingchunk-hue.github.io/chunk.github.io   # 项目页面 URL
root: /chunk.github.io/                                   # 项目页面根路径
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Theme
theme: butterfly

# Deployment
deploy:
  type: git
  repo: git@github.com:subingchunk-hue/chunk.github.io.git
  branch: main

# 压缩优化 - 提升网站性能
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
    - '*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'
